import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import {defineConfig, loadEnv} from 'vite';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function generateImagesListPlugin() {
  return {
    name: 'generate-images-list',
    buildStart() {
      const dir = path.resolve(__dirname, 'public/images');
      let files: string[] = [];
      if (fs.existsSync(dir)) {
        files = fs.readdirSync(dir)
          .filter(file => {
            const ext = path.extname(file).toLowerCase();
            return ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.svg'].includes(ext);
          });
      }
      const fileContent = `// This file is auto-generated by vite.config.ts. Do not edit manually.
export const LOCAL_IMAGES = ${JSON.stringify(files, null, 2)};
`;
      fs.writeFileSync(path.resolve(__dirname, 'src/images-list.ts'), fileContent);
    }
  };
}

export default defineConfig(({mode}) => {
  const env = loadEnv(mode, '.', '');
  return {
    base: '/',
    plugins: [react(), tailwindcss(), generateImagesListPlugin()],
    define: {
      'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY || ''),
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },
    build: {
      outDir: 'dist',
      assetsDir: 'assets',
      emptyOutDir: true,
      sourcemap: false,
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modifyâfile watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
    },
  };
});
